name       : zita-convolver
version    : 4.0.3
release    : 3
source     :
    - https://kokkinizita.linuxaudio.org/linuxaudio/downloads/zita-convolver-4.0.3.tar.bz2 : 9aa11484fb30b4e6ef00c8a3281eebcfad9221e3937b1beb5fe21b748d89325f
license    : GPL-3.0-or-later
component  : programming.library
summary    : A fast, partitioned convolution engine library
description: |
    A fast, partitioned convolution engine library
builddeps  :
    - pkgconfig(fftw3)
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-unnecessary-ldconfig-change-prefix-while-we-a.patch
build      : |
    %make -C source
install    : |
    %make_install -C source
